도서 리뷰 수정/삭제 기능 구현
likelion-backend-2nd-project-team11/book-more pull request #60
Opened 2023-01-25 01:36 UTC by Senna97

## 개요

도서 리뷰 수정 기능 구현
도서 리뷰 삭제 기능 구현

## 작업 내용

- 리뷰 작성자에 한해, 리뷰 id로 조회하여 리뷰가 수정/삭제되도록 기능을 구현했습니다.

## 체크리스트

- [x] 코드 포맷팅 확인
- [x] 불필요한 import 제거
- [x] 테스트 코드 작성 및 통과

2023-01-26 06:43 UTC, menuhwang requested changes
수정 부탁드립니다 👍

2023-01-26 06:43 UTC, menuhwang commented on backend/src/main/java/site/bookmore/bookmore/books/entity/Chart.java
> +    public void update(Chart chart) {
Patch 방식적용을 위해 update메소드들 안에 null 체크 로직이 필요한데 제가 컬럼 타입을 int로 설계한 바람에 null 체크를 못 하셨군요.

Chart 컬럼을 Integer로 바꾸고 null 체크 로직을 추가해주세요.

2023-01-26 06:43 UTC, menuhwang commented on backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
> +    private void updateSpoiler(boolean spoiler) {
마찬가지로 Boolean으로 바꾸고 null 체크 추가해주세요.

다음부턴 꼼꼼히 잘 짜도록 하겠습니다. 😢

2023-01-26 07:27 UTC, Senna97 commented on backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
> +    private void updateSpoiler(boolean spoiler) {
수정 완료했습니다!

2023-01-26 14:57 UTC, menuhwang commented on backend/src/main/java/site/bookmore/bookmore/books/entity/Review.java
> +    private void updateSpoiler(boolean spoiler) {
확인했습니다.

2023-01-26 14:57 UTC, menuhwang approved these changes

2023-01-27 07:04 UTC, yjyj1023 approved these changes
리뷰 완료

2023-01-27 07:07 UTC, merged